#Project Euler - 29
#Keith Petro - 2016/10/21
#Problem Name: Distinct powers
#Description: How many distinct terms are in the sequence generated by
#a^b for 2 <= a <= 100 and 2 <= b <= 100?

def get_number_of_distinct_terms(a_min, a_max, b_min, b_max):
	distinct_terms = []
	for a in range(a_min, a_max + 1):
		for b in range (b_min, b_max + 1):
			term = a ** b
			if not term in distinct_terms:
				distinct_terms.append(term)

	return len(distinct_terms)

print(get_number_of_distinct_terms(2, 100, 2, 100))